### ISSUE TITLE
std::system_error при вызове set_mode с режимом hd1080i30

### ISSUE THREAD

**Issue by algts** [RC-MODULE/media.hpp#1]
Проблема в video.hpp 77 строчка:
((video_mode::hd_1080i25 == vm || video_mode::hd_1080i25 == vm || video_mode::hd_1080p30 == vm || video_mode::hd_1080p25 == vm) ? 1080 :

**Comment by kirm** [comment]
А какая именно проблема?

**Comment by kirm** [comment]
Fixed
