### ISSUE TITLE
Вылет после нескольких секунд (минут) работы 

### ISSUE THREAD

**Issue by algts** [RC-MODULE/media.hpp#2]
Где-то в сдк происходит вылет после нескольких 10+ секунд работы, если в push последовательно передаются 2 пакета с идентичным pts. Программа либо просто вылетает с segfault, либо иногда пишет сообщения типа double free or corruption (fasttop): 0xb4900be0 ***

**Comment by algts** [comment]
Глюк плавающий, выскакивает далеко не всегда. Пока удалось выяснить, что часто вылетает в отрезке от 1300 обработанных пакетов и до 2000 пакетов.

**Comment by kirm** [comment]
А вы может прислать код, дамп, стек потому что такому количеству информации я ничего сказать не могу.

**Comment by algts** [comment]
Проблема в том, что в стеке ничего нет, только 2 строчки с двумя вопросами. Я бы сам с радостью вам сказал, где именно проблема, но есть только дисассембл непонятно чего.

**Comment by kirm** [comment]
Вы можете сделать пример на котором эта проблема воспроизводится?

**Comment by algts** [comment]
Я попробую на вашей программе для работы с ртп, я помню, что она бывало тоже вылетала с segfault. Если это так, то пришлю вам файл, на котором происходит вылет. Вылет практически всегда происходит после 4 и более минут воспроизведения.

**Comment by kirm** [comment]
Я посмотрел стек что вы прислали, насколько я понимаю там произошло следущее:  по какой-то причине стал уничтожаться объекты библиотеки (самый верхний вызов кода библиотеки деструктор system_clock) и видимо media::video::sink был уничтожен до system_clock. В расписании system_clock лежали кадры для показа выделенные video::sink. К сожалению до 9de85f70cc960a7efcac1b7aa1528f94ff20993e вызов деструктора кадра после деструктора video::sink приводил к segfault.
